// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/tasks.proto

package taskspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailPayload) Reset() {
	*x = EmailPayload{}
	mi := &file_proto_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailPayload) ProtoMessage() {}

func (x *EmailPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailPayload.ProtoReflect.Descriptor instead.
func (*EmailPayload) Descriptor() ([]byte, []int) {
	return file_proto_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *EmailPayload) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *EmailPayload) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailPayload) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ImagePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePayload) Reset() {
	*x = ImagePayload{}
	mi := &file_proto_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePayload) ProtoMessage() {}

func (x *ImagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePayload.ProtoReflect.Descriptor instead.
func (*ImagePayload) Descriptor() ([]byte, []int) {
	return file_proto_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *ImagePayload) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImagePayload) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImagePayload) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type ReportPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportType    string                 `protobuf:"bytes,1,opt,name=report_type,json=reportType,proto3" json:"report_type,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportPayload) Reset() {
	*x = ReportPayload{}
	mi := &file_proto_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPayload) ProtoMessage() {}

func (x *ReportPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPayload.ProtoReflect.Descriptor instead.
func (*ReportPayload) Descriptor() ([]byte, []int) {
	return file_proto_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *ReportPayload) GetReportType() string {
	if x != nil {
		return x.ReportType
	}
	return ""
}

func (x *ReportPayload) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ReportPayload) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type WebhookPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	SimulateCode  int32                  `protobuf:"varint,3,opt,name=simulate_code,json=simulateCode,proto3" json:"simulate_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookPayload) Reset() {
	*x = WebhookPayload{}
	mi := &file_proto_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookPayload) ProtoMessage() {}

func (x *WebhookPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookPayload.ProtoReflect.Descriptor instead.
func (*WebhookPayload) Descriptor() ([]byte, []int) {
	return file_proto_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *WebhookPayload) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebhookPayload) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *WebhookPayload) GetSimulateCode() int32 {
	if x != nil {
		return x.SimulateCode
	}
	return 0
}

type NotificationPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationPayload) Reset() {
	*x = NotificationPayload{}
	mi := &file_proto_tasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPayload) ProtoMessage() {}

func (x *NotificationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPayload.ProtoReflect.Descriptor instead.
func (*NotificationPayload) Descriptor() ([]byte, []int) {
	return file_proto_tasks_proto_rawDescGZIP(), []int{4}
}

func (x *NotificationPayload) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *NotificationPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationPayload) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type NotificationBatchPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int32                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Messages      []string               `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Group         string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationBatchPayload) Reset() {
	*x = NotificationBatchPayload{}
	mi := &file_proto_tasks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationBatchPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationBatchPayload) ProtoMessage() {}

func (x *NotificationBatchPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationBatchPayload.ProtoReflect.Descriptor instead.
func (*NotificationBatchPayload) Descriptor() ([]byte, []int) {
	return file_proto_tasks_proto_rawDescGZIP(), []int{5}
}

func (x *NotificationBatchPayload) GetUserIds() []int32 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *NotificationBatchPayload) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *NotificationBatchPayload) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *NotificationBatchPayload) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

var File_proto_tasks_proto protoreflect.FileDescriptor

const file_proto_tasks_proto_rawDesc = "" +
	"\n" +
	"\x11proto/tasks.proto\x12\x12asynqtest.tasks.v1\"L\n" +
	"\fEmailPayload\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"N\n" +
	"\fImagePayload\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\"j\n" +
	"\rReportPayload\x12\x1f\n" +
	"\vreport_type\x18\x01 \x01(\tR\n" +
	"reportType\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"_\n" +
	"\x0eWebhookPayload\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12#\n" +
	"\rsimulate_code\x18\x03 \x01(\x05R\fsimulateCode\"b\n" +
	"\x13NotificationPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\"}\n" +
	"\x18NotificationBatchPayload\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x05R\auserIds\x12\x1a\n" +
	"\bmessages\x18\x02 \x03(\tR\bmessages\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05groupB1Z/github.com/asynq-test/internal/tasks/pb;taskspbb\x06proto3"

var (
	file_proto_tasks_proto_rawDescOnce sync.Once
	file_proto_tasks_proto_rawDescData []byte
)

func file_proto_tasks_proto_rawDescGZIP() []byte {
	file_proto_tasks_proto_rawDescOnce.Do(func() {
		file_proto_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tasks_proto_rawDesc), len(file_proto_tasks_proto_rawDesc)))
	})
	return file_proto_tasks_proto_rawDescData
}

var file_proto_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_tasks_proto_goTypes = []any{
	(*EmailPayload)(nil),             // 0: asynqtest.tasks.v1.EmailPayload
	(*ImagePayload)(nil),             // 1: asynqtest.tasks.v1.ImagePayload
	(*ReportPayload)(nil),            // 2: asynqtest.tasks.v1.ReportPayload
	(*WebhookPayload)(nil),           // 3: asynqtest.tasks.v1.WebhookPayload
	(*NotificationPayload)(nil),      // 4: asynqtest.tasks.v1.NotificationPayload
	(*NotificationBatchPayload)(nil), // 5: asynqtest.tasks.v1.NotificationBatchPayload
}
var file_proto_tasks_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tasks_proto_init() }
func file_proto_tasks_proto_init() {
	if File_proto_tasks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tasks_proto_rawDesc), len(file_proto_tasks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_tasks_proto_goTypes,
		DependencyIndexes: file_proto_tasks_proto_depIdxs,
		MessageInfos:      file_proto_tasks_proto_msgTypes,
	}.Build()
	File_proto_tasks_proto = out.File
	file_proto_tasks_proto_goTypes = nil
	file_proto_tasks_proto_depIdxs = nil
}
